# Generated by Django 2.2.10 on 2020-04-23 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_ariticlepost_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='ariticlepost',
            name='total_views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
