# Generated by Django 2.2.10 on 2020-04-23 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_auto_20200423_0646'),
    ]

    operations = [
        migrations.AddField(
            model_name='ariticlepost',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
